### PR TITLE
Normalize YAML in Travis config

### PR DESCRIPTION
**Pull request by kytrinyx**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Ouch. Ignore this for a sec.

**Comment by kytrinyx** [comment]
I don't understand what went wrong here :/

**Comment by verdammelt** [comment]
Well that's intresting. Curent master still builds fine. Rebuilding this PR still fails. Somehow this change causes CIM/Travis to work differently (and badly).

**Comment by arguello** [comment]
sbcl32 and ccl32 failed with the error:
```E: Unable to locate package libc6```

https://travis-ci.org/exercism/xlisp/jobs/95295340#L297-L299
https://travis-ci.org/exercism/xlisp/jobs/95295342#L297-L299

The installs for clisp and clisp32 aborted:
```Do you want to continue? [Y/n] Abort.```

https://travis-ci.org/exercism/xlisp/jobs/95295344#L306
https://travis-ci.org/exercism/xlisp/jobs/95295345#L300

There's a message at the top of each build job stating:
```This job ran on our new platform for Legacy Precise builds. Please read our blog post for more information.```
https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

That likely broke the builds.

It's interesting that the build dist is `precise`, but it actually seems to be using `trusty`:
https://travis-ci.org/exercism/xlisp/jobs/95295340#L8-L15

Anyway, adding the `-y` flag to the `apt-get` commands in https://github.com/luismbo/cl-travis/blob/master/install.sh should resolve the clisp issues... and might resolve the sbcl32 and ccl32 issues.

**Comment by kytrinyx** [comment]
Ah, right. They must have changed that very recently! I'll try switching to the containerized build in a branch to see if that works.

**Comment by wobh** [comment]
Well, I feel a bit embarrassed. Apparently the only thing wrong is that we needed to normalize the rest of travis.yml: https://github.com/wobh/xlisp/tree/xlisp-91-normalize-YAML-in-Travis-config

**Pull request merged**
