### PR TITLE
Relative load in test files for code under test

### PR DESCRIPTION
**Pull request by spacebat**

### CODE REVIEW

**Comment by verdammelt** [comment]
Would a simpler `(merge "..." *load-pathname*)` be sufficient?

**Comment by spacebat** [comment]
Unfortunately if merge-pathnames is passed NIL as its second argument you get an error, and `*load-pathname*` is nil unless loading is in progress. To make your suggestion friendly to interactive evaluation, we'd have to wrap it in an `(eval-when (:load-toplevel :compile-toplevel) ...)` form, which I try to avoid where possible.

**Comment by verdammelt** [comment]
Sorry I didn't just test it out myself before asking. 

I don't like, what I feel is, the ugliness of the expression. I'm thinking of the experience of the person new to Common Lisp coming to the track - will this expression leave the person with the feeling "Wow - Common Lisp is really complicated" or will they just ignore it as some ritualistic boilerplate?  (But in the latter case - will they start copying it everywhere?

I guess the ugliness was already started with the feature check...

As for utility function use in other tracks - I'll check and repot back.

**Comment by verdammelt** [comment]
@spacebat can you explain your workflow - because in my testing I'm not sure if I'm seeing the issue. Perhaps because the way I use my environment (SBCL & SLIME) is different.

From the issue #126 you mention that you set `*default-pathname-defaults*` to some location. In my checking no matter what my `*default-pathname-defaults*` is set to if I set my working directory in SLIME (via `cd`) it sets `*default-pathname-defaults*`. I don't normally set the defaults so either I'm starting SLIME in the correct directory or changing to the correct directory.

I want to keep the code that exercism submitters see as simple and clear as possible; mostly they are *not* experienced Common Lisp users. You appear to be an experienced Lisp user (thanks for submitting to the track!) and I want to be careful that we don't make changes to help the expert at the detriment of the beginner.

**Comment by spacebat** [comment]
@verdammelt I just run M-x slime-load-file and use ido to browse to the test file (which might be the default if I have run the command with the test file in the current buffer), which then fails because I haven't run slime-cd first. My goal is to make the test file just work however it is loaded or evaluated, but I understand your concern - its more code and doesn't look approachable for new users. If we can't easily create an xlisp library for this sort of utility, perhaps the instructions should just mention the need to need to run cd in slime or start lisp in the exercise directory - I haven't found that mentioned anywhere but could have missed it.

Thanks for thinking about it though :)

**Comment by verdammelt** [comment]
I think if we created some xlisp library with a helper function for loading the 'production' code - then we'd still have the problem of how to load that library :)

Unless we push it to quicklisp - but that seems over-the-top.

Let me review the README - maybe we can put some documentation about SLIME usage.

**Comment by spacebat** [comment]
Lets update the docs then. I'll close this PR.

**Pull request closed without merging**
