### PR TITLE
test install script

### PR DESCRIPTION
**Pull request by arguello**
Testing Travis CI

### CODE REVIEW

**Comment by arguello** [comment]
The tests passed - all I did was modify the install script:
https://github.com/luismbo/cl-travis/compare/master...arguello:master

I'm not sure if this is the best way, and a little concerned that this broke in the 1st place - but it works.

**Comment by wobh** [comment]
Yeah, this seems like a known thing: https://github.com/luismbo/cl-travis/issues/9. I'd prefer to try to get it fixed upstream than fork. I'm intrigued by the last comment there about alternatives. Maybe we should look into that...

**Comment by arguello** [comment]
+1 for an upstream fix.

This test had nothing to do with sudo, though - I just added the `-y` flag to `apt-get` - gets around the continue prompts. Applying that upstream might cause it to break for others?

Looks like someone had an idea for native lisp support, but the project seems to have died down:
http://blog.cddr.org/2015/07/28/native-travisci-support-for-common-lisp/
https://github.com/lisp-travis

Couldn't find any other alternatives to cl-travis.

I'm willing to help with whatever is decided.

**Comment by verdammelt** [comment]
In the issue @wobh referred to above the author of cl-travis says "folks are working on better alternatives to cl-travis.". Any ideas what they mean by that? If we don't know I, or someone else, ough to ask...

**Comment by wobh** [comment]
One thing is that cl-travis installs lisps itself as system lisps, only using CIM to set the default lisp. (for example: [107: install_abcl](https://github.com/luismbo/cl-travis/blob/master/install.sh#L107), and [116: cim use abcl-system --default](https://github.com/luismbo/cl-travis/blob/master/install.sh#L116)). I've only just started looking into available features on TravisCI

- https://docs.travis-ci.com/user/languages/community-supported-languages/
- https://docs.travis-ci.com/user/apt/

and correlating those with cl-travis and CIM (see https://github.com/KeenS/CIM/blob/master/scripts/cim_lib_install), and I'm starting to wonder if we even need cl-travis? What required that cl-travis install lisps as system lisps?

**Comment by arguello** [comment]
Would this be a good alternative? [Using Travis CI with Roswell] (https://gist.github.com/fukamachi/52dce85caf477043ffeb)

**Comment by verdammelt** [comment]
Roswell looks like it could replace CIM. But something about the fact the project is also a CL web framework - not just a implmentaiton switcher, seems odd to me.

What if we fork CIM and use that? Then when/if CIM integrated the fix we can switch back to CIM.

**Comment by arguello** [comment]
> What if we fork cl-travis and use that? Then when/if cl-travis integrated the fix we can switch back to cl-travis.

Sounds like a good idea.

We can move the `sudo apt-get` commands out of the install script:
https://docs.travis-ci.com/user/customizing-the-build/#Installing-Packages-Using-apt

Is it necessary to install both the 32-bit and 64-bit versions of each lisp?

**Comment by wobh** [comment]
I'll try to setup xlisp-travis this weekend.

**Comment by arguello** [comment]
:tada:

**Comment by verdammelt** [comment]
@wobh good luck! If I can help let me know.

**Comment by wobh** [comment]
So, it turns out the problem was that I committed a wonkily formatted travis.yml that only caused problems when the YAML directive separator [---](http://www.yaml.org/spec/1.2/spec.html#id2760395) was added to the top of the file. Once the file was reindented, the builds worked without any need to make changes to cl-travis.

**Comment by arguello** [comment]
So, those jobs ran on the legacy infrastructure, and all passed. Half of the jobs that ran on the "new platform for Legacy Precise builds" failed, and I think every job that ran on the containerized build infrastructure failed.

Do the yaml updates guarantee that the jobs will always run on the legacy infrastructure?

**Comment by wobh** [comment]
I think they will until TravisCI requires us to add `sudo: true` to them. https://docs.travis-ci.com/user/migrating-from-legacy

I'm still working on xlisp-travis, I just noticed that the we could resolve/merge #91 independently.

**Comment by verdammelt** [comment]
@wobh good catch on the YAML formatting thing.

**Comment by arguello** [comment]
Awesome - good catch for sure.

**Comment by wobh** [comment]
So my plan was to to try to come up with an install script that would use cim to install lisps. This would let us get away from cl-travis's use of `sudo` and thus get us on with containers. However I've had problems working with cim. Locally, I get a build error with `cim install clisp`, and `cim install ccl` doesn't seem to work at all. Furthermore, I'm not sure cim supports installing x86 versions. We can get around this. We could drop support for 32-bit platforms. This has taken more time than I hoped it would, and I've had less time than I hoped to take with it.

**Comment by verdammelt** [comment]
@wobh As you may have seen in #58 I had the same problems with CIM. I don't think it is up to the task of installing Lisps.

What is the state of this pull request?

**Comment by wobh** [comment]
I'll close it. I think it was a good idea, but we're trying to fix something that's not really broken, just somewhat undesirable. At this remove, it seems like the thing to do is support the effort for native CL on TravisCI.

**Pull request closed without merging**
