### PR TITLE
ABCL seems to be a valid implementation.

### PR DESCRIPTION
**Pull request by verdammelt**

### CODE REVIEW

**Comment by wobh** [comment]
Whups! I merged the two fixes for CCL and CLisp, but now this change has a small conflict.

**Comment by verdammelt** [comment]
No problem - I'll take care of it. I sort of screwed it up with the CLisp change myself.

**Comment by verdammelt** [comment]
Looks like I fixed things up on this branch.

**Comment by verdammelt** [comment]
For the record - I also tried allegro & cmucl  on travis - but those failed. The problems seemed to be more like issues with getting the implementations running under travis, or with lisp-unit rather than with our code.

**Pull request merged**
