### PR TITLE
Add new accumulate exercise.

### PR DESCRIPTION
**Pull request by verdammelt**
Very simple exercise - perhaps we should make it one of the first.

### CODE REVIEW

**Comment by verdammelt** [comment]
Maybe we shouldn't include this one at all. It is really simple due to `mapcar`.

Or maybe we make it more interesting by having it take different types of sequences (returning a sequence of the same type)? what would allow the use of `typecase` or generic functions.

**Comment by yurrriq** [comment]
Or can we add "don't use `mapcar`" or even `map*` to the README somehow? There are some fun ways to implement this "manually." :+1: for making it the first exercise too.

**Comment by verdammelt** [comment]
It seems that @canweriotnow added a note to the readme (https://github.com/exercism/x-common/blob/master/accumulate.md) stating that `mapcar` was just fine.

I'm leaning toward making this a "foregone" exercise. I don't think we should include it.

**Comment by yurrriq** [comment]
Cool. :+1: for exclusion then.

**Comment by wobh** [comment]
Agree we should exclude it.

**Comment by verdammelt** [comment]
I'll change this pull request to be an exclusion and then merge it in.

**Pull request closed without merging**
