### PR TITLE
Binary problem.

### PR DESCRIPTION
**Pull request by verdammelt**
I wrote several solutions - which do people think should be the 'official' one? Or maybe we leave all of them in the example file? But even in that case one should be left as the one not commented out.

### CODE REVIEW

**Comment by wobh** [comment]
http://lisptips.com/post/44261316742/how-do-i-convert-an-integer-to-a-list-of-bits

**Comment by wobh** [comment]
I thought I read somewhere that the example files aren't meant to be "canonical". I've been thinking of them as "meta-tests" in the sense that, if we change the testing suite, the example file will help us make sure we're still doing something reasonable. But I do see the case that making them into "good" examples would be useful for people contributing future exercises.

**Comment by verdammelt** [comment]
I always thought of the example file to be "a solution" that one could look at if one got stuck. But now I don't know where the user could actually see this example file... I don't seem to get them when I do `exercism fetch`.

Thanks for the link - I never remember all the `ash` and `logand` type functions - my brain never seems to think of them (dumb brain).

**Comment by kytrinyx** [comment]
The only thing the example file is used for at the moment, is as a sanity check for the test suite. It would be a shame to have an unsolvable test suite. People could technically go look at the solution in the github repo, but I doubt that many do.

**Pull request merged**
