### PR TITLE
xlisp #26: setup xlisp-test and cl-travis

### PR DESCRIPTION
**Pull request by wobh**
- setup bin/xlisp-test
- setup tests with xlisp-test feature
- setup .travis.yml
- extensive testing
- move robot print-object for specs
- allow failures on non-SBCL implementations for the time being

### CODE REVIEW

**Comment by verdammelt** [comment]
What is meant by "allow problem builds for the time being"?

**Comment by wobh** [comment]
It should probably read "allow failures on non-SBCL implementations for the time being".

**Comment by verdammelt** [comment]
Would it be possible to merge this in with *only* those implementations that work fine and open issues to fix those that don't? And have the build fail if anything is wrong?

**Comment by wobh** [comment]
You mean remove the other implementations from ".travis.yml" entirely? We'd just add them back, and have to fix whatever the issues are, under the issue of "support clisp" or whatever. If you would prefer this procedurally, that's fine by me, I just want to clarify my next action and hear your rationale.

**Comment by verdammelt** [comment]
I'm probably misunderstanding something.

If the build will not fail for known broken implementations (e.g. clisp) - will it fail if SBCL has a problem?

My rational is that if we are going to include an automated build with a test suite I want it to fail when there is a problem with known good environments. I would not like a build that is always failing because of known bad implementations or always passes even if there are problems.

**Comment by wobh** [comment]
Ah. Check out the build page: https://travis-ci.org/exercism/xlisp

There's two SBCL environments (one's 32 bit) and the tests all pass on them.

You can see an example of failing tests on SBCL back in the build history here. I spent some time trying to build with deliberately introduced bugs to cause the tests to fail, which they do. Here's the first build where they fail as expected: 

https://travis-ci.org/wobh/xlisp/jobs/64213987

Here's the build after I removed the bugs:

https://travis-ci.org/wobh/xlisp/builds/64214537

You can see that SBCL passes while all others fail. Only thing I've done since is catch up with the recently added exercises and added the failing implementations to the "allowed failures" list. Once merged we can file the issues to fix Clisp, CCL and the others.

**Comment by verdammelt** [comment]
Ah! OK, thanks for clearing up my confusion. I've got no problems with this now.

**Comment by verdammelt** [comment]
(As an aside: I just scanned the CCL & ECL failures (looks the same) and for some reason 'bottles' is capitalized?! Looking at the example code I don't see anything that *might* prompt an implementation to do that... weird.)

**Comment by wobh** [comment]
I've been observing a protocol where I don't merge my own pull requests. That seems slightly silly now that I type it out, but if you're ready to move on with it, either merge or let me know and I'll do it. Maybe it would be a good idea to work out some kind of signal.

**Comment by verdammelt** [comment]
That seems like a fine protocol. 

Pull Request signal? http://publicsafety.tufts.edu/police/files/pubsafe_up__16.jpg

(I was hoping for something more entertaining to appear from a google image search of 'pull request signal' but *sigh* no such luck).

**Comment by wobh** [comment]
Thanks! I'll file some new issues for getting the other implementations working. We should be able to check off a number of items on your checklist. Exciting times!

**Comment by verdammelt** [comment]
Thanks. See my notes above about what I've debugged of CCL & ECL problems - I think if the example code did not rely upon `~(~)` it would be portable to those two implementations (and their bugs). The CLisp problem appeared easy to fix as well - at worst we remove the offending, but unused, method.

**Pull request merged**
