### PR TITLE
gh-138: setup travis with ros

### PR DESCRIPTION
**Pull request by wobh**
clasp and cmu-bin will not be supported for now

### CODE REVIEW

**Comment by verdammelt** [comment]
This looks pretty good.

Looks like we can get rid of that helper script that installed CIM.

Also any changes to the docs needed?

**Comment by wobh** [comment]
I'm working on the docs.

**Comment by wobh** [comment]
I felt like I had to simplify the README docs a bit, taking out the part about how to locally test all installed lisp implementations with Roswell. I couldn't find a way to do that like we could with CIM. We might just have to advise people to set up TravisCI for their fork.

**Comment by verdammelt** [comment]
The doc changes look good. But before I merge let me "test" them by following them and see how it work. Will try to do that tonight/tomorrow night.

**Pull request merged**
